version: '3'

services:
  javaback:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: td
      
      

networks:
  default:
    driver: bridge