spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    
    username: postgres
    password: td
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  tomcat:
    accesslog:
      enabled: true